# The following environment variables are substituted if present
# * CONSENSUS: default to raft
# * QUORUM_DOCKER_IMAGE: default to quorumengineering/quorum:latest
# * TX_MANAGER_DOCKER_IMAGE: default to quorumengineering/tessera:latest
version: "3.7"
x-quorum-def:
  &quorum-def
  restart: "on-failure"
  image: "${QUORUM_DOCKER_IMAGE:-quorumengineering/quorum:latest}"
  expose:
    - "21000"
    - "50400"
  entrypoint:
    - /bin/sh
    - -c
    - |
      DDIR=/qdata/dd
      rm -rf $${DDIR}
      mkdir -p $${DDIR}/keystore
      mkdir -p $${DDIR}/geth
      cp /config/raft/nodekey$${NODE_ID} $${DDIR}/geth/nodekey
      cp /config/keys/key1 $${DDIR}/keystore/
      cat /config/permissioned-nodes.json | sed 's/^\(.*\)@.*\?\(.*\)raftport=5040\([0-9]\)\(.*\)$$/\1@172.16.239.1\3:21000?discport=0\4/g' > $${DDIR}/static-nodes.json
      cp $${DDIR}/static-nodes.json $${DDIR}/permissioned-nodes.json
      cat $${DDIR}/static-nodes.json
      NETWORK_ID=$$(cat /config/istanbul-genesis.json | grep chainId | awk -F " " '{print $$2}' | awk -F "," '{print $$1}')
      geth --datadir $${DDIR} init /config/istanbul-genesis.json
      geth \
        --identity node$${NODE_ID} \
        --datadir $${DDIR} \
        --permissioned \
        --nodiscover \
        --verbosity 5 \
        --networkid $$NETWORK_ID \
        --rpc \
        --rpcaddr 0.0.0.0 \
        --rpcport 8545 \
        --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul \
        --emitcheckpoints \
        --port 21000 \
        --unlock 0 \
        --password /config/passwords.txt \
        --istanbul.blockperiod 1 \
        --mine \
        --minerthreads 1 \
        --syncmode full
x-tx-manager-tessera-def:
  &tx-manager-tessera-def
  image: "${TX_MANAGER_DOCKER_IMAGE:-quorumengineering/tessera:latest}"
  expose:
    - "9000"
  restart: "no"
  entrypoint:
    - /bin/sh
    - -c
    - |
      DDIR=/qdata/tm
      rm -rf $${DDIR}
      mkdir -p $${DDIR}
      cp /config/keys/tm$${NODE_ID}.pub $${DDIR}/tm.pub
      cp /config/keys/tm$${NODE_ID}.key $${DDIR}/tm.key
      cat <<EOF > $${DDIR}/tessera-config.json
      {
          "useWhiteList": false,
          "jdbc": {
              "username": "sa",
              "password": "",
              "url": "jdbc:h2:./$${DDIR}/db;MODE=Oracle;TRACE_LEVEL_SYSTEM_OUT=0"
          },
          "server": {
              "port": 9000,
              "hostName": "http://$$(hostname -i)",
              "sslConfig": {
                  "tls": "OFF",
                  "generateKeyStoreIfNotExisted": true,
                  "serverKeyStore": "$${DDIR}/server-keystore",
                  "serverKeyStorePassword": "quorum",
                  "serverTrustStore": "$${DDIR}/server-truststore",
                  "serverTrustStorePassword": "quorum",
                  "serverTrustMode": "TOFU",
                  "knownClientsFile": "$${DDIR}/knownClients",
                  "clientKeyStore": "$${DDIR}/client-keystore",
                  "clientKeyStorePassword": "quorum",
                  "clientTrustStore": "$${DDIR}/client-truststore",
                  "clientTrustStorePassword": "quorum",
                  "clientTrustMode": "TOFU",
                  "knownServersFile": "$${DDIR}/knownServers"
              }
          },
          "peer": [
              {
                  "url": "http://txmanager1:9000"
              },
              {
                  "url": "http://txmanager2:9000"
              },
              {
                  "url": "http://txmanager3:9000"
              },
              {
                  "url": "http://txmanager4:9000"
              },
              {
                  "url": "http://txmanager5:9000"
              },
              {
                  "url": "http://txmanager6:9000"
              },
              {
                  "url": "http://txmanager7:9000"
              }
          ],
          "keys": {
              "passwords": [],
              "keyData": [
                  {
                      "config": $$(cat $${DDIR}/tm.key),
                      "publicKey": "$$(cat $${DDIR}/tm.pub)"
                  }
              ]
          },
          "alwaysSendTo": [],
          "unixSocketFile": "$${DDIR}/tm.ipc"
      }
      EOF
      java -Xms128M -Xmx128M -jar /tessera/tessera-app.jar -configfile $${DDIR}/tessera-config.json
x-tx-manager-constellation-def:
  &tx-manager-constellation-def
  image: "${TX_MANAGER_DOCKER_IMAGE:-quorumengineering/constellation:latest}"
  expose:
    - "9000"
  restart: "no"
  entrypoint:
    - /bin/sh
    - -c
    - |
      DDIR=/qdata/tm
      rm -rf $${DDIR}
      mkdir -p $${DDIR}
      echo "socket=\"$${DDIR}/tm.ipc\"\npublickeys=[\"/config/keys/tm$${NODE_ID}.pub\"]\n" > $${DDIR}/tm.conf
      constellation-node \
        --url=http://$$(hostname -i):9000/ \
        --port=9000 \
        --socket=$${DDIR}/tm.ipc \
        --othernodes=http://172.16.239.101:9000/,http://172.16.239.102:9000/,http://172.16.239.103:9000/,http://172.16.239.104:9000/,http://172.16.239.105:9000/ \
        --publickeys=/config/keys/tm$${NODE_ID}.pub \
        --privatekeys=/config/keys/tm$${NODE_ID}.key \
        --storage=$${DDIR} \
        --verbosity=4
services:
  node1:
    << : *quorum-def
    hostname: node1
    ports:
      - "22001:8545"
    volumes:
      - 1:/qdata
      - ./examples/7nodes:/config:ro
    depends_on:
      - txmanager1
    environment:
      - PRIVATE_CONFIG=/qdata/tm/tm.ipc
      - NODE_ID=1
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.11
  txmanager1:
    << : *tx-manager-tessera-def
    hostname: txmanager1
    volumes:
      - 1:/qdata
      - ./examples/7nodes:/config:ro
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.101
    environment:
      - NODE_ID=1
  node2:
    << : *quorum-def
    hostname: node2
    ports:
      - "22002:8545"
    volumes:
      - 2:/qdata
      - ./examples/7nodes:/config:ro
    depends_on:
      - txmanager2
    environment:
      - PRIVATE_CONFIG=/qdata/tm/tm.ipc
      - NODE_ID=2
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.12
  txmanager2:
    << : *tx-manager-tessera-def
    hostname: txmanager2
    volumes:
      - 2:/qdata
      - ./examples/7nodes:/config:ro
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.102
    environment:
      - NODE_ID=2
  node3:
    << : *quorum-def
    hostname: node3
    ports:
      - "22003:8545"
    volumes:
      - 3:/qdata
      - ./examples/7nodes:/config:ro
    depends_on:
      - txmanager3
    environment:
      - PRIVATE_CONFIG=/qdata/tm/tm.ipc
      - NODE_ID=3
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.13
  txmanager3:
    << : *tx-manager-tessera-def
    hostname: txmanager3
    volumes:
      - 3:/qdata
      - ./examples/7nodes:/config:ro
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.103
    environment:
      - NODE_ID=3
  node4:
    << : *quorum-def
    hostname: node4
    ports:
      - "22004:8545"
    volumes:
      - 4:/qdata
      - ./examples/7nodes:/config:ro
    depends_on:
      - txmanager4
    environment:
      - PRIVATE_CONFIG=/qdata/tm/tm.ipc
      - NODE_ID=4
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.14
  txmanager4:
    << : *tx-manager-tessera-def
    hostname: txmanager4
    volumes:
      - 4:/qdata
      - ./examples/7nodes:/config:ro
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.104
    environment:
      - NODE_ID=4
  node5:
    << : *quorum-def
    hostname: node5
    ports:
      - "22005:8545"
    volumes:
      - 5:/qdata
      - ./examples/7nodes:/config:ro
    depends_on:
      - txmanager5
    environment:
      - PRIVATE_CONFIG=/qdata/tm/tm.ipc
      - NODE_ID=5
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.15
  txmanager5:
    << : *tx-manager-tessera-def
    hostname: txmanager5
    volumes:
      - 5:/qdata
      - ./examples/7nodes:/config:ro
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.105
    environment:
      - NODE_ID=5
  node6:
    << : *quorum-def
    hostname: node6
    ports:
      - "22006:8545"
    volumes:
      - 6:/qdata
      - ./examples/7nodes:/config:ro
    depends_on:
      - txmanager6
    environment:
      - PRIVATE_CONFIG=/qdata/tm/tm.ipc
      - NODE_ID=6
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.16
  txmanager6:
    << : *tx-manager-tessera-def
    hostname: txmanager6
    volumes:
      - 6:/qdata
      - ./examples/7nodes:/config:ro
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.106
    environment:
      - NODE_ID=6
  node7:
    << : *quorum-def
    hostname: node7
    ports:
      - "22007:8545"
    volumes:
      - 7:/qdata
      - ./examples/7nodes:/config:ro
    depends_on:
      - txmanager7
    environment:
      - PRIVATE_CONFIG=/qdata/tm/tm.ipc
      - NODE_ID=7
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.17
  txmanager7:
    << : *tx-manager-tessera-def
    hostname: txmanager7
    volumes:
      - 7:/qdata
      - ./examples/7nodes:/config:ro
    networks:
      quorum-examples-net:
        ipv4_address: 172.16.239.107
    environment:
      - NODE_ID=7
networks:
  quorum-examples-net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24
volumes:
  "1":
  "2":
  "3":
  "4":
  "5":
  "6":
  "7":
